name: GCC-15/16

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 6'
env:
  PATH: ${{ env.HOME }}/.local/bin:${{ env.PATH }}
  ACE_ROOT: ${{ github.workspace }}/ACE_TAO/ACE
  MPC_ROOT: ${{ github.workspace }}/ACE_TAO/MPC
  TAO_ROOT: ${{ github.workspace }}/ACE_TAO/TAO
  X11_BASE_ROOT: ${{ github.workspace }}
  RIDL_ROOT: ${{ github.workspace }}/ridl
  TAOX11_ROOT: ${{ github.workspace }}/taox11
  INSTALL_PREFIX: ${{ github.workspace }}/stagedir
  CMAKE_INSTALL_PREFIX: ${{ github.workspace }}/stagedir
  CXX: g++
  CC: gcc

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        version: [15, 16]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc${{ matrix.version }}
      options: --user root

    # Prevent jobs from canceling each other
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.version }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python, venv, and pip
        run: |
          apt-get update -q
          apt-get install -y python3 python3-pip python3-venv python-is-python3 symlinks

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      # - name: Add ~/.local/bin to PATH
      #   run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create venv for pip install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      # - name: Run test suite
      #   env:
      #     CC: gcc
      #     CXX: g++
      #     PATH: $HOME/.local/bin:$PATH
      #   run: |
      #     . .venv/bin/activate
      #     ./build-taox11-on-linux.sh

      - name: Run brix11 configure
        run: |
          $X11_BASE_ROOT/bin/brix11 configure # -W aceroot=$ACE_ROOT -W taoroot=$TAO_ROOT -W mpcroot=$MPC_ROOT
      - name: Print brix11 configuration
        run: |
          $X11_BASE_ROOT/bin/brix11 env -- configure -P
      - name: Run brix11 gen build
        run: |
          $X11_BASE_ROOT/bin/brix11 gen build workspace.mwc
          # -- gen build $TAOX11_ROOT/examples -- gen build $TAOX11_ROOT/orbsvcs/tests -- gen build $TAOX11_ROOT/tests
      - name: Run brix11 make
        run: |
          $X11_BASE_ROOT/bin/brix11 make -N $X11_BASE_ROOT
          # -- make -N $TAOX11_ROOT/examples -- make -N $TAOX11_ROOT/orbsvcs/tests -- make -N $TAOX11_ROOT/tests
      - name: Run cmake install
        run: |
          . .venv/bin/activate
          export PATH="$X11_BASE_ROOT/bin:$X11_BASE_ROOT/lib:$TAOX11_ROOT/bin:$ACE_ROOT/bin:$ACE_ROOT/lib:$PATH"
          export LD_LIBRARY_PATH=${X11_BASE_ROOT}/lib:${ACE_ROOT}/lib:/usr/local/lib:/usr/lib
          $X11_BASE_ROOT/bin/brix11 execute cmake -B build -S . -G Ninja -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=OFF -Wdev -Wdeprecated
          $X11_BASE_ROOT/bin/brix11 execute cmake --build build --target all
          $X11_BASE_ROOT/bin/brix11 execute cmake --install build --prefix ${INSTALL_PREFIX}
      - name: Run ctest
        run: |
          . .venv/bin/activate
          export PATH="${INSTALL_PREFIX}/bin:${PATH}"
          export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:/usr/local/lib:/usr/lib"
          $X11_BASE_ROOT/bin/brix11 execute ctest --test-dir build --output-on-failure
      - name: Run cpack
        run: |
          . .venv/bin/activate
          $X11_BASE_ROOT/bin/brix11 execute cmake --build build --target package
