name: GCC-15/16

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 6'

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        version: [15, 16]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc${{ matrix.version }}

    # Prevent jobs from canceling each other
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.version }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python, venv, and pip
        run: |
          apt-get update -q
          apt-get install -y python3 python3-pip python3-venv python3-is-python sysmlinks

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Create venv for pip install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run test suite
        env:
          CC: gcc
          CXX: g++
          PATH: $HOME/.local/bin:$PATH
        run: |
          . .venv/bin/activate
          ./build-taox11-on-linux.sh
